# validator.py — GENERATED by tools/genschema.py — do not edit; depends on (none).
"""Validate instances against the generated JSON Schema subset used by Cassette."""

import json
import math
import re
from pathlib import Path

_SCHEMAS = {}


def _schemas():
    if not _SCHEMAS:
        for path in sorted(Path(__file__).parent.glob("*.json")):
            if path.name != "MANIFEST.json":
                _SCHEMAS[path.stem] = json.loads(path.read_text(encoding="utf-8"))
    return _SCHEMAS


def _validate(schema, value, path, root_schema=None, depth=0):
    if depth > 64:
        return [f"{path}: nesting exceeds the 64-level contract bound"]
    if root_schema is None:
        root_schema = schema
    if "$ref" in schema:
        if schema["$ref"].startswith("#/$defs/"):
            name = schema["$ref"].removeprefix("#/$defs/")
            target = root_schema.get("$defs", {}).get(name)
            if target is None:
                return [f"{path}: unknown local schema reference {schema['$ref']!r}"]
            return _validate(target, value, path, root_schema, depth + 1)
        target = Path(schema["$ref"]).stem
        if target not in _schemas():
            return [f"{path}: unknown schema reference {schema['$ref']!r}"]
        target_schema = _schemas()[target]
        return _validate(target_schema, value, path, target_schema, depth + 1)
    if "anyOf" in schema:
        if any(
            not _validate(candidate, value, path, root_schema, depth + 1)
            for candidate in schema["anyOf"]
        ):
            return []
        return [f"{path}: value does not match any allowed shape"]
    kind = schema.get("type")
    if kind == "object":
        if not isinstance(value, dict):
            return [f"{path}: expected object"]
        properties = schema.get("properties", {})
        patterns = schema.get("patternProperties", {})
        matched = {
            name: [shape for pattern, shape in patterns.items() if re.fullmatch(pattern, name)]
            for name in value
        }
        defects = [
            f"{path}.{name}: unknown field"
            for name in sorted(set(value) - set(properties))
            if schema.get("additionalProperties") is False and not matched[name]
        ]
        if len(value) < schema.get("minProperties", 0):
            defects.append(f"{path}: requires at least {schema['minProperties']} properties")
        if len(value) > schema.get("maxProperties", len(value)):
            defects.append(f"{path}: permits at most {schema['maxProperties']} properties")
        defects.extend(
            f"{path}.{name}: required field missing"
            for name in schema.get("required", [])
            if name not in value
        )
        for name in sorted(set(value) & set(properties)):
            defects.extend(
                _validate(properties[name], value[name], f"{path}.{name}", root_schema, depth + 1)
            )
        for name in sorted(set(value) - set(properties)):
            for shape in matched[name]:
                defects.extend(
                    _validate(shape, value[name], f"{path}.{name}", root_schema, depth + 1)
                )
        return defects
    if kind == "array":
        if not isinstance(value, list):
            return [f"{path}: expected array"]
        defects = []
        if len(value) < schema.get("minItems", 0):
            defects.append(f"{path}: requires at least {schema['minItems']} items")
        if len(value) > schema.get("maxItems", len(value)):
            defects.append(f"{path}: permits at most {schema['maxItems']} items")
        if "items" in schema:
            for index, item in enumerate(value):
                defects.extend(
                    _validate(schema["items"], item, f"{path}[{index}]", root_schema, depth + 1)
                )
        if schema.get("uniqueItems") and any(
            item == prior for index, item in enumerate(value) for prior in value[:index]
        ):
            defects.append(f"{path}: items must be unique")
        return defects
    if kind == "null":
        return [] if value is None else [f"{path}: expected null"]
    expected = {"string": str, "integer": int, "number": (int, float), "boolean": bool}.get(kind)
    if expected is not None:
        if isinstance(value, bool) and kind in ("integer", "number"):
            return [f"{path}: bool is not a {kind}"]
        if not isinstance(value, expected):
            return [f"{path}: expected {kind}"]
        defects = []
        if kind == "string" and len(value) < schema.get("minLength", 0):
            defects.append(f"{path}: string is shorter than {schema['minLength']}")
        if kind == "string" and len(value) > schema.get("maxLength", len(value)):
            defects.append(f"{path}: string is longer than {schema['maxLength']}")
        if kind == "string" and "pattern" in schema and re.fullmatch(schema["pattern"], value) is None:
            defects.append(f"{path}: string does not match {schema['pattern']!r}")
        if kind == "number" and not math.isfinite(value):
            defects.append(f"{path}: number must be finite")
        if "minimum" in schema and value < schema["minimum"]:
            defects.append(f"{path}: value is below {schema['minimum']}")
        if "maximum" in schema and value > schema["maximum"]:
            defects.append(f"{path}: value is above {schema['maximum']}")
        if "enum" in schema and value not in schema["enum"]:
            defects.append(f"{path}: {value!r} not in enum")
        return defects
    if kind is None:
        return []
    return [f"{path}: validator does not implement schema type {kind!r}"]


def validate(kind, obj):
    """Return every structural defect; an empty list means the instance conforms."""
    if kind not in _schemas():
        return [f"unknown contract kind {kind!r}"]
    return _validate(_schemas()[kind], obj, kind)
