# validator.py — GENERATED by tools/genschema.py — do not edit; depends on (none).
"""Structural validation for the generated contracts. validate(kind, obj) -> list of defects."""

import json
from pathlib import Path

_TYPES = {
    "str": str,
    "int": int,
    "bool": bool,
    "number": (int, float),
    "object": dict,
    "array": list,
}
_SCHEMAS = {}


def _schemas():
    if not _SCHEMAS:
        for path in sorted(Path(__file__).parent.glob("*.json")):
            if path.name == "MANIFEST.json":
                continue
            data = json.loads(path.read_text(encoding="utf-8"))
            _SCHEMAS[data["kind"]] = data["fields"]
    return _SCHEMAS


def validate(kind, obj, _path=""):
    schemas = _schemas()
    if kind not in schemas:
        return [f"{_path}unknown contract kind {kind!r}"]
    if not isinstance(obj, dict):
        return [f"{_path}{kind}: instance must be an object"]
    fields = schemas[kind]
    defects = []
    for name in obj:
        if name not in fields:
            defects.append(f"{_path}{kind}.{name}: unknown field")
    for name, spec in fields.items():
        if name not in obj:
            if spec.get("required", True):
                defects.append(f"{_path}{kind}.{name}: required field missing")
            continue
        value = obj[name]
        if spec["type"] == "any":
            continue
        if spec["type"] == "ref":
            defects.extend(validate(spec["ref"], value, f"{_path}{kind}.{name}: "))
            continue
        expected = _TYPES[spec["type"]]
        if isinstance(value, bool) and spec["type"] in ("int", "number"):
            defects.append(f"{_path}{kind}.{name}: bool is not a {spec['type']}")
        elif not isinstance(value, expected):
            defects.append(f"{_path}{kind}.{name}: expected {spec['type']}")
        elif "enum" in spec and value not in spec["enum"]:
            defects.append(f"{_path}{kind}.{name}: {value!r} not in enum")
    return defects
