# genschema.py — emits the Q6/Q9/Q31/Q50/Q57 JSON Schemas, validator, and integrity manifest; depends on errors.py.
"""Generate Cassette's machine contracts. Files under schema/ are never hand-edited.

The emitted documents are JSON Schema Draft 2020-12 contracts. The generated validator executes
the small schema subset used here without adding a runtime dependency. MANIFEST.json binds every
generated byte; tools/ledger.py also regenerates the directory so editing a schema and its digest
together still fails.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import errors

GENERATED_NOTE = "GENERATED by tools/genschema.py — do not edit"
SCHEMA_DIALECT = "https://json-schema.org/draft/2020-12/schema"
SCHEMA_BASE = "https://recluse.studio/cassette/schema/v1"
REMOTE_METADATA_FIELDS = [
    "identity",
    "total_bytes",
    "artifact_count",
    "artifact_digests",
    "format",
    "architecture",
    "total_parameters",
    "active_parameters",
    "dtype_quantization",
    "context",
    "modalities",
    "operators",
    "custom_code",
    "tokenizer",
    "processor",
    "template",
    "license",
    "gating",
    "revision_ancestry",
    "training_precision",
    "source_validators",
]


def text(*, enum: list[str] | None = None, empty: bool = False) -> dict:
    shape: dict = {"type": "string"}
    if not empty:
        shape["minLength"] = 1
    if enum is not None:
        shape["enum"] = enum
    return shape


def array(items: dict | None = None, *, minimum: int | None = None) -> dict:
    shape: dict = {"type": "array"}
    if items is not None:
        shape["items"] = items
    if minimum is not None:
        shape["minItems"] = minimum
    return shape


def ref(kind: str) -> dict:
    return {"$ref": f"{kind}.json"}


def record(
    title: str,
    question: str,
    properties: dict[str, dict],
    *,
    optional: tuple[str, ...] = (),
) -> dict:
    return {
        "$schema": SCHEMA_DIALECT,
        "$comment": f"{GENERATED_NOTE}; authority: {question}",
        "title": title,
        "type": "object",
        "additionalProperties": False,
        "properties": properties,
        "required": sorted(set(properties) - set(optional)),
    }


REMOTE_FIELD = record(
    "Remote metadata field",
    "Q50",
    {
        "value": {},
        "trust": text(enum=["ABSENT", "DECLARED", "EVIDENCE_DIGESTED", "PARSED"]),
        "authority": text(),
    },
    optional=("value",),
)

CONTRACTS: dict[str, dict] = {
    "error": record(
        "Canonical error",
        "Q6/Q32",
        {
            "code": text(enum=sorted(errors.CODES)),
            "object_id": text(),
            "failed_invariant": text(),
            "retryability": text(enum=sorted(errors.RETRYABILITY)),
            "detail": text(empty=True),
        },
    ),
    "request": record(
        "Control request",
        "Q6",
        {
            "protocol_version": text(),
            "operation": text(),
            "idempotency_key": text(),
            "target": text(),
            "arguments": {"type": "object"},
        },
        optional=("target",),
    ),
    "operation": record(
        "Asynchronous operation",
        "Q6",
        {
            "operation_id": text(),
            "kind": text(),
            "state": text(
                enum=["CANCELLED", "FAILED", "PAUSED", "PENDING", "RUNNING", "SUCCEEDED"]
            ),
            "progress": {"type": "number"},
            "result": {"type": "object"},
            "error": ref("error"),
        },
        optional=("result", "error"),
    ),
    "capability_profile": record(
        "Canonical capability profile",
        "Q31",
        {
            "protocol_version": text(),
            "model_refs": array(text()),
            "modalities": array(text()),
            "context": {"type": "object"},
            "reasoning": {},
            "tools": {},
            "structured_output": {},
            "streaming": {},
            "cancellation": {},
            "training": {},
            "source": {},
            "performance_tiers": array({"type": "object"}),
        },
    ),
    "run_request": record(
        "Canonical run request",
        "Q31",
        {
            "idempotency_key": text(),
            "model_ref": text(),
            "input": {},
            "context_ref": text(),
            "generation": {"type": "object"},
            "reasoning": {},
            "output_schema": {"type": "object"},
            "tools": array({"type": "object"}),
        },
        optional=("context_ref", "reasoning", "output_schema", "tools"),
    ),
    "run_event": record(
        "Canonical run event",
        "Q6/Q31",
        {
            "run_id": text(),
            "sequence": {"type": "integer", "minimum": 0},
            "type": text(
                enum=[
                    "started",
                    "reasoning_delta",
                    "output_delta",
                    "tool_call",
                    "tool_result",
                    "usage",
                    "completed",
                    "cancelled",
                    "failed",
                ]
            ),
            "payload": {"type": "object"},
        },
    ),
    "source_descriptor": record(
        "Normalized source descriptor",
        "Q9",
        {
            "kind": text(enum=["huggingface", "ollama", "tinker", "extension"]),
            "locator": text(),
            "revision": text(),
            "artifact_selector": {},
            "credential_ref": text(),
            "license_acceptance_ref": text(),
            "expected_identity": text(),
        },
        optional=(
            "revision",
            "artifact_selector",
            "credential_ref",
            "license_acceptance_ref",
            "expected_identity",
        ),
    ),
    "remote_metadata_field": REMOTE_FIELD,
    "remote_metadata": record(
        "Remote metadata preflight record",
        "Q50",
        {
            **{name: ref("remote_metadata_field") for name in REMOTE_METADATA_FIELDS},
            "conflicts": array(
                record(
                    "Retained metadata conflict",
                    "Q50 acceptance_check",
                    {
                        "field": text(enum=REMOTE_METADATA_FIELDS),
                        "candidates": array(ref("remote_metadata_field"), minimum=2),
                    },
                )
            ),
        },
    ),
    "tensor_span": record(
        "Tensor page span",
        "Q57",
        {
            "page_digest": text(),
            "offset": {"type": "integer", "minimum": 0},
            "length": {"type": "integer", "minimum": 1},
            "tensor_offset": {"type": "integer", "minimum": 0},
        },
    ),
    "tensor_map": record(
        "Semantic tensor map",
        "Q57",
        {
            "semantic_tensor_id": text(),
            "shape": array({"type": "integer", "minimum": 0}),
            "dtype": text(),
            "codec": text(),
            "plane": {},
            "spans": array(ref("tensor_span")),
        },
    ),
    "root": {
        **record(
            "Immutable cartridge root manifest",
            "Q57",
            {
                "identity": text(),
                "parents": array(text()),
                "provenance": {"type": "object"},
                "semantic_assets": {"type": "object"},
                "tensor_maps": array(ref("tensor_map")),
                "operators": array(),
                "plans": array(),
                "deltas": array(),
                "integrity_root": text(),
            },
        ),
        "x-cassette-canonicalization": "RFC8785",
    },
}

VALIDATOR_SRC = '''# validator.py — {note}; depends on (none).
"""Validate instances against the generated JSON Schema subset used by Cassette."""

import json
from pathlib import Path

_SCHEMAS = {{}}


def _schemas():
    if not _SCHEMAS:
        for path in sorted(Path(__file__).parent.glob("*.json")):
            if path.name != "MANIFEST.json":
                _SCHEMAS[path.stem] = json.loads(path.read_text(encoding="utf-8"))
    return _SCHEMAS


def _validate(schema, value, path):
    if "$ref" in schema:
        target = Path(schema["$ref"]).stem
        if target not in _schemas():
            return [f"{{path}}: unknown schema reference {{schema['$ref']!r}}"]
        return _validate(_schemas()[target], value, path)
    kind = schema.get("type")
    if kind == "object":
        if not isinstance(value, dict):
            return [f"{{path}}: expected object"]
        properties = schema.get("properties", {{}})
        defects = [
            f"{{path}}.{{name}}: unknown field"
            for name in sorted(set(value) - set(properties))
            if schema.get("additionalProperties") is False
        ]
        defects.extend(
            f"{{path}}.{{name}}: required field missing"
            for name in schema.get("required", [])
            if name not in value
        )
        for name in sorted(set(value) & set(properties)):
            defects.extend(_validate(properties[name], value[name], f"{{path}}.{{name}}"))
        return defects
    if kind == "array":
        if not isinstance(value, list):
            return [f"{{path}}: expected array"]
        defects = []
        if len(value) < schema.get("minItems", 0):
            defects.append(f"{{path}}: requires at least {{schema['minItems']}} items")
        if "items" in schema:
            for index, item in enumerate(value):
                defects.extend(_validate(schema["items"], item, f"{{path}}[{{index}}]"))
        return defects
    expected = {{"string": str, "integer": int, "number": (int, float), "boolean": bool}}.get(kind)
    if expected is not None:
        if isinstance(value, bool) and kind in ("integer", "number"):
            return [f"{{path}}: bool is not a {{kind}}"]
        if not isinstance(value, expected):
            return [f"{{path}}: expected {{kind}}"]
        defects = []
        if kind == "string" and len(value) < schema.get("minLength", 0):
            defects.append(f"{{path}}: string is shorter than {{schema['minLength']}}")
        if "minimum" in schema and value < schema["minimum"]:
            defects.append(f"{{path}}: value is below {{schema['minimum']}}")
        if "maximum" in schema and value > schema["maximum"]:
            defects.append(f"{{path}}: value is above {{schema['maximum']}}")
        if "enum" in schema and value not in schema["enum"]:
            defects.append(f"{{path}}: {{value!r}} not in enum")
        return defects
    if kind is None:
        return []
    return [f"{{path}}: validator does not implement schema type {{kind!r}}"]


def validate(kind, obj):
    """Return every structural defect; an empty list means the instance conforms."""
    if kind not in _schemas():
        return [f"unknown contract kind {{kind!r}}"]
    return _validate(_schemas()[kind], obj, kind)
'''


def emit(outdir: Path) -> dict[str, str]:
    """Write every generated file and return its name-to-SHA-256 integrity map."""
    outdir.mkdir(parents=True, exist_ok=True)
    written: dict[str, str] = {}

    def put(name: str, content: str) -> None:
        (outdir / name).write_text(content, encoding="utf-8")
        written[name] = hashlib.sha256(content.encode("utf-8")).hexdigest()

    for kind, schema in sorted(CONTRACTS.items()):
        document = {"$id": f"{SCHEMA_BASE}/{kind}.json", **schema}
        put(f"{kind}.json", json.dumps(document, ensure_ascii=False, indent=2, sort_keys=True) + "\n")
    put("validator.py", VALIDATOR_SRC.format(note=GENERATED_NOTE))
    (outdir / "MANIFEST.json").write_text(
        json.dumps(written, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return written


def main() -> int:
    outdir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parent.parent / "schema"
    emit(outdir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
