# genschema.py — emits schema/ contracts, validator, and manifest from the ledger's shapes (Q6/Q9/Q31/Q50/Q57); depends on errors.py.
"""Generate the machine contracts. schema/ is data plus one generated validator; never hand-edit.

Shapes come from the research ledger: Error and Request/Operation (Q6), RunEvent (Q31),
SourceDescriptor (Q9), RemoteMetadata field records (Q50), and the cartridge Root manifest (Q57).
Every emitted file is recorded by digest in schema/MANIFEST.json; tools/ledger.py fails closed on
any drift. Regeneration is deterministic: same inputs, same bytes.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import errors

GENERATED_NOTE = "GENERATED by tools/genschema.py — do not edit"

CONTRACTS: dict[str, dict[str, dict]] = {
    "error": {
        "code": {"type": "str", "enum": sorted(errors.CODES)},
        "object_id": {"type": "str"},
        "failed_invariant": {"type": "str"},
        "retryability": {"type": "str", "enum": sorted(errors.RETRYABILITY)},
        "detail": {"type": "str"},
    },
    "request": {
        "protocol_version": {"type": "str"},
        "operation": {
            "type": "str",
            "enum": [
                "acquire", "activate", "cancel", "capabilities", "prepare", "recover",
                "remove", "resolve_source", "run", "status", "train",
            ],
        },
        "idempotency_key": {"type": "str"},
        "target": {"type": "str", "required": False},
        "arguments": {"type": "object"},
    },
    "operation": {
        "operation_id": {"type": "str"},
        "kind": {"type": "str"},
        "state": {
            "type": "str",
            "enum": ["CANCELLED", "FAILED", "PAUSED", "PENDING", "RUNNING", "SUCCEEDED"],
        },
        "progress": {"type": "number"},
        "result": {"type": "object", "required": False},
        "error": {"type": "ref", "ref": "error", "required": False},
    },
    "run_event": {
        "run_id": {"type": "str"},
        "sequence": {"type": "int"},
        "type": {
            "type": "str",
            "enum": [
                "cancelled", "completed", "failed", "output_delta", "reasoning_delta",
                "started", "tool_call", "tool_result", "usage",
            ],
        },
        "payload": {"type": "object"},
    },
    "source_descriptor": {
        "kind": {"type": "str", "enum": ["extension", "huggingface", "ollama", "tinker"]},
        "locator": {"type": "str"},
        "revision": {"type": "str", "required": False},
        "artifact_selector": {"type": "str", "required": False},
        "credential_ref": {"type": "str", "required": False},
        "license_acceptance_ref": {"type": "str", "required": False},
        "expected_identity": {"type": "str", "required": False},
    },
    "remote_metadata_field": {
        "name": {"type": "str"},
        "value": {"type": "any", "required": False},
        "trust": {"type": "str", "enum": ["ABSENT", "DECLARED", "EVIDENCE_DIGESTED", "PARSED"]},
        "authority": {"type": "str"},
    },
    "root": {
        "identity": {"type": "str"},
        "parents": {"type": "array"},
        "provenance": {"type": "object"},
        "semantic_assets": {"type": "object"},
        "tensor_maps": {"type": "array"},
        "operators": {"type": "array"},
        "plans": {"type": "array"},
        "deltas": {"type": "array"},
        "integrity_root": {"type": "str"},
    },
}

VALIDATOR_SRC = '''# validator.py — {note}; depends on (none).
"""Structural validation for the generated contracts. validate(kind, obj) -> list of defects."""

import json
from pathlib import Path

_TYPES = {{
    "str": str,
    "int": int,
    "bool": bool,
    "number": (int, float),
    "object": dict,
    "array": list,
}}
_SCHEMAS = {{}}


def _schemas():
    if not _SCHEMAS:
        for path in sorted(Path(__file__).parent.glob("*.json")):
            if path.name == "MANIFEST.json":
                continue
            data = json.loads(path.read_text(encoding="utf-8"))
            _SCHEMAS[data["kind"]] = data["fields"]
    return _SCHEMAS


def validate(kind, obj, _path=""):
    schemas = _schemas()
    if kind not in schemas:
        return [f"{{_path}}unknown contract kind {{kind!r}}"]
    if not isinstance(obj, dict):
        return [f"{{_path}}{{kind}}: instance must be an object"]
    fields = schemas[kind]
    defects = []
    for name in obj:
        if name not in fields:
            defects.append(f"{{_path}}{{kind}}.{{name}}: unknown field")
    for name, spec in fields.items():
        if name not in obj:
            if spec.get("required", True):
                defects.append(f"{{_path}}{{kind}}.{{name}}: required field missing")
            continue
        value = obj[name]
        if spec["type"] == "any":
            continue
        if spec["type"] == "ref":
            defects.extend(validate(spec["ref"], value, f"{{_path}}{{kind}}.{{name}}: "))
            continue
        expected = _TYPES[spec["type"]]
        if isinstance(value, bool) and spec["type"] in ("int", "number"):
            defects.append(f"{{_path}}{{kind}}.{{name}}: bool is not a {{spec['type']}}")
        elif not isinstance(value, expected):
            defects.append(f"{{_path}}{{kind}}.{{name}}: expected {{spec['type']}}")
        elif "enum" in spec and value not in spec["enum"]:
            defects.append(f"{{_path}}{{kind}}.{{name}}: {{value!r}} not in enum")
    return defects
'''


def emit(outdir: Path) -> dict[str, str]:
    """Write all generated files; return name -> sha256 manifest (also written)."""
    outdir.mkdir(parents=True, exist_ok=True)
    written: dict[str, str] = {}

    def put(name: str, content: str) -> None:
        (outdir / name).write_text(content, encoding="utf-8")
        written[name] = hashlib.sha256(content.encode("utf-8")).hexdigest()

    for kind, fields in sorted(CONTRACTS.items()):
        body = {"_generated": GENERATED_NOTE, "kind": kind, "fields": fields}
        put(f"{kind}.json", json.dumps(body, indent=2, sort_keys=True) + "\n")
    put("validator.py", VALIDATOR_SRC.format(note=GENERATED_NOTE))
    (outdir / "MANIFEST.json").write_text(
        json.dumps(written, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return written


def main() -> int:
    outdir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parent.parent / "schema"
    emit(outdir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
