# genschema.py — emits Q6/Q9/Q19/Q30/Q31/Q33/Q40/Q50/Q57/Q77 contracts and generated tables; depends on errors.py.
"""Generate Cassette's machine contracts. Files under schema/ are never hand-edited.

The emitted documents are JSON Schema Draft 2020-12 contracts. The generated validator executes
the small schema subset used here without adding a runtime dependency. MANIFEST.json binds every
generated byte; tools/ledger.py also regenerates the directory so editing a schema and its digest
together still fails.
"""

from __future__ import annotations

import hashlib
import json
import pprint
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import errors

GENERATED_NOTE = "GENERATED by tools/genschema.py — do not edit"
SCHEMA_DIALECT = "https://json-schema.org/draft/2020-12/schema"
SCHEMA_BASE = "https://recluse.studio/cassette/schema/v1"
REMOTE_METADATA_FIELDS = [
    "identity",
    "total_bytes",
    "artifact_count",
    "artifact_digests",
    "format",
    "architecture",
    "total_parameters",
    "active_parameters",
    "dtype_quantization",
    "context",
    "modalities",
    "operators",
    "custom_code",
    "tokenizer",
    "processor",
    "template",
    "license",
    "gating",
    "revision_ancestry",
    "training_precision",
    "source_validators",
]
Q77_FIELDS = [
    "cassette_protocol",
    "adapter_version",
    "model_revision",
    "source_parent",
    "execution_mode",
    "plan_id",
    "performance_tier",
    "training_tier",
    "modalities",
    "input_limits",
    "context_limit",
    "reasoning_fields",
    "reasoning_history_policy",
    "tool_schema",
    "structured_output",
    "sampling",
    "streaming",
    "cancellation",
    "conversation_state_contract",
]
Q77_PROVENANCE_STATUSES = [
    "BEST_EFFORT",
    "EXACT",
    "PROVIDER_MANAGED",
    "UNKNOWN",
    "UNSUPPORTED",
]
MAX_IDENTIFIER_BYTES = 256
MAX_TEXT_BYTES = 4096
MAX_TABLE_ROWS = 1_048_576
MAX_U64 = 18_446_744_073_709_551_615
MLX_RUNTIME = {
    "name": "mlx",
    "package": "mlx==0.31.0",
    "release_commit": "365d6f29b47686a9f5401f6a9ec5825fee162d69",
    "apple_features": ["apple_silicon", "metal"],
}
Q40_MODES = [
    "BYTE_IDENTICAL_LAYOUT",
    "EXACT_NATIVE_SPARSITY",
    "EXACT_QUANTIZED_LAYOUT",
    "NATIVE_PREDICTIVE_PREFETCH",
    "COMPILED_CERTIFIED",
]
DISPATCH_ROWS = [
    {
        "case_id": "mlx.matmul.f32.2x3_3x2",
        "operator": "matmul",
        "runtime_symbols": ["mlx.core.matmul"],
        "input_dtypes": ["float32", "float32"],
        "input_shapes": [[2, 3], [3, 2]],
        "output_dtype": "float32",
        "output_shape": [2, 2],
        "parameters": {},
        "absolute_tolerance": 1e-6,
        "relative_tolerance": 1e-6,
    },
    {
        "case_id": "mlx.matmul.f32.2x4_4x4",
        "operator": "matmul",
        "runtime_symbols": ["mlx.core.matmul"],
        "input_dtypes": ["float32", "float32"],
        "input_shapes": [[2, 4], [4, 4]],
        "output_dtype": "float32",
        "output_shape": [2, 4],
        "parameters": {},
        "absolute_tolerance": 1e-6,
        "relative_tolerance": 1e-6,
    },
    {
        "case_id": "mlx.add.f32.2x4",
        "operator": "add",
        "runtime_symbols": ["mlx.core.add"],
        "input_dtypes": ["float32", "float32"],
        "input_shapes": [[2, 4], [2, 4]],
        "output_dtype": "float32",
        "output_shape": [2, 4],
        "parameters": {},
        "absolute_tolerance": 1e-6,
        "relative_tolerance": 1e-6,
    },
    {
        "case_id": "mlx.silu.f32.2x4",
        "operator": "activation",
        "runtime_symbols": ["mlx.nn.silu"],
        "input_dtypes": ["float32"],
        "input_shapes": [[2, 4]],
        "output_dtype": "float32",
        "output_shape": [2, 4],
        "parameters": {},
        "absolute_tolerance": 1e-6,
        "relative_tolerance": 1e-6,
    },
    {
        "case_id": "mlx.quantized_matmul.affine4.f32.1x32_2x32",
        "operator": "quantized_matmul",
        "runtime_symbols": ["mlx.core.quantized_matmul"],
        "input_dtypes": ["float32", "uint32", "float32", "float32"],
        "input_shapes": [[1, 32], [2, 4], [2, 1], [2, 1]],
        "output_dtype": "float32",
        "output_shape": [1, 2],
        "parameters": {"bits": 4, "group_size": 32, "mode": "affine", "transpose": True},
        "absolute_tolerance": 1e-3,
        "relative_tolerance": 1e-6,
    },
    {
        "case_id": "mlx.rms_norm.f32.2x4",
        "operator": "norm",
        "runtime_symbols": ["mlx.core.fast.rms_norm"],
        "input_dtypes": ["float32", "float32"],
        "input_shapes": [[2, 4], [4]],
        "output_dtype": "float32",
        "output_shape": [2, 4],
        "parameters": {"eps": 1e-5},
        "absolute_tolerance": 1e-5,
        "relative_tolerance": 1e-5,
    },
    {
        "case_id": "mlx.rope.traditional.f32.1x1x2x4",
        "operator": "rope",
        "runtime_symbols": ["mlx.core.fast.rope"],
        "input_dtypes": ["float32"],
        "input_shapes": [[1, 1, 2, 4]],
        "output_dtype": "float32",
        "output_shape": [1, 1, 2, 4],
        "parameters": {
            "base": 10000.0,
            "dims": 4,
            "offset": 0,
            "scale": 1.0,
            "traditional": True,
        },
        "absolute_tolerance": 1e-5,
        "relative_tolerance": 1e-5,
    },
    {
        "case_id": "mlx.rope.traditional.f32.1x1x2x4.offset1",
        "operator": "rope",
        "runtime_symbols": ["mlx.core.fast.rope"],
        "input_dtypes": ["float32"],
        "input_shapes": [[1, 1, 2, 4]],
        "output_dtype": "float32",
        "output_shape": [1, 1, 2, 4],
        "parameters": {
            "base": 10000.0,
            "dims": 4,
            "offset": 1,
            "scale": 1.0,
            "traditional": True,
        },
        "absolute_tolerance": 1e-5,
        "relative_tolerance": 1e-5,
    },
    {
        "case_id": "mlx.attention.f32.1x1x2x2",
        "operator": "attention",
        "runtime_symbols": ["mlx.core.fast.scaled_dot_product_attention"],
        "input_dtypes": ["float32", "float32", "float32"],
        "input_shapes": [[1, 1, 2, 2], [1, 1, 2, 2], [1, 1, 2, 2]],
        "output_dtype": "float32",
        "output_shape": [1, 1, 2, 2],
        "parameters": {"scale": 0.7071067811865476},
        "absolute_tolerance": 1e-5,
        "relative_tolerance": 1e-5,
    },
    {
        "case_id": "mlx.attention.causal.f32.1x1x2x4",
        "operator": "attention",
        "runtime_symbols": ["mlx.core.fast.scaled_dot_product_attention"],
        "input_dtypes": ["float32", "float32", "float32"],
        "input_shapes": [[1, 1, 2, 4], [1, 1, 2, 4], [1, 1, 2, 4]],
        "output_dtype": "float32",
        "output_shape": [1, 1, 2, 4],
        "parameters": {"mask": "causal", "scale": 0.5},
        "absolute_tolerance": 1e-5,
        "relative_tolerance": 1e-5,
    },
    {
        "case_id": "mlx.conv1d.f32.1x4x1_1x2x1",
        "operator": "convolution",
        "runtime_symbols": ["mlx.core.conv1d"],
        "input_dtypes": ["float32", "float32"],
        "input_shapes": [[1, 4, 1], [1, 2, 1]],
        "output_dtype": "float32",
        "output_shape": [1, 3, 1],
        "parameters": {"dilation": 1, "groups": 1, "padding": 0, "stride": 1},
        "absolute_tolerance": 1e-6,
        "relative_tolerance": 1e-6,
    },
    {
        "case_id": "mlx.embedding.f32_u32.4x3_2",
        "operator": "embedding",
        "runtime_symbols": ["mlx.core.take"],
        "input_dtypes": ["float32", "uint32"],
        "input_shapes": [[4, 3], [2]],
        "output_dtype": "float32",
        "output_shape": [2, 3],
        "parameters": {"axis": 0},
        "absolute_tolerance": 0.0,
        "relative_tolerance": 0.0,
    },
    {
        "case_id": "mlx.embedding.f32_u32.4x4_2",
        "operator": "embedding",
        "runtime_symbols": ["mlx.core.take"],
        "input_dtypes": ["float32", "uint32"],
        "input_shapes": [[4, 4], [2]],
        "output_dtype": "float32",
        "output_shape": [2, 4],
        "parameters": {"axis": 0},
        "absolute_tolerance": 0.0,
        "relative_tolerance": 0.0,
    },
    {
        "case_id": "mlx.categorical.f32_u32.2x3_2",
        "operator": "sampling",
        "runtime_symbols": ["mlx.core.random.categorical"],
        "input_dtypes": ["float32", "uint32"],
        "input_shapes": [[2, 3], [2]],
        "output_dtype": "uint32",
        "output_shape": [2],
        "parameters": {"axis": -1},
        "absolute_tolerance": 0.0,
        "relative_tolerance": 0.0,
    },
    {
        "case_id": "mlx.autograd_sum.f32.2x3",
        "operator": "autograd",
        "runtime_symbols": ["mlx.core.grad", "mlx.core.sum"],
        "input_dtypes": ["float32"],
        "input_shapes": [[2, 3]],
        "output_dtype": "float32",
        "output_shape": [2, 3],
        "parameters": {},
        "absolute_tolerance": 0.0,
        "relative_tolerance": 0.0,
    },
    {
        "case_id": "mlx.sgd.f32.3",
        "operator": "optimizer",
        "runtime_symbols": ["mlx.optimizers.SGD.apply_gradients"],
        "input_dtypes": ["float32", "float32"],
        "input_shapes": [[3], [3]],
        "output_dtype": "float32",
        "output_shape": [3],
        "parameters": {"learning_rate": 0.25},
        "absolute_tolerance": 1e-6,
        "relative_tolerance": 1e-6,
    },
]
DISPATCH_DIGEST = "sha256:" + hashlib.sha256(
    json.dumps(
        {"runtime": MLX_RUNTIME, "rows": DISPATCH_ROWS},
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")
).hexdigest()
OPERATOR_DISPATCH_RECORD = {
    "dispatch_version": "q30-v1",
    "runtime_name": MLX_RUNTIME["name"],
    "runtime_version": MLX_RUNTIME["package"].split("==", 1)[1],
    "runtime_commit": MLX_RUNTIME["release_commit"],
    "dispatch_digest": DISPATCH_DIGEST,
    "case_ids": [row["case_id"] for row in DISPATCH_ROWS],
    "apple_features": MLX_RUNTIME["apple_features"],
}
CERTIFICATE_DIMENSION_GROUPS = ("mathematics", "resources", "tables", "physical")
CERTIFICATE_DIMENSIONS_BEGIN = "<!-- CASSETTE_CERTIFICATE_DIMENSIONS_BEGIN -->"
CERTIFICATE_DIMENSIONS_END = "<!-- CASSETTE_CERTIFICATE_DIMENSIONS_END -->"
MAX_CERTIFICATE_AUTHORITY_BYTES = 8_192
MAX_CERTIFICATE_DIMENSIONS_PER_GROUP = 64


def load_certificate_dimensions(maths_path: Path | None = None) -> dict[str, list[str]]:
    """Parse the single bounded certificate-dimension authority in MATHS.md section 8."""
    path = maths_path or Path(__file__).resolve().parent.parent / "MATHS.md"
    source = path.read_text(encoding="utf-8")
    if source.count(CERTIFICATE_DIMENSIONS_BEGIN) != 1:
        raise ValueError("MATHS.md requires exactly one certificate-dimensions begin marker")
    if source.count(CERTIFICATE_DIMENSIONS_END) != 1:
        raise ValueError("MATHS.md requires exactly one certificate-dimensions end marker")
    start = source.index(CERTIFICATE_DIMENSIONS_BEGIN) + len(CERTIFICATE_DIMENSIONS_BEGIN)
    end = source.index(CERTIFICATE_DIMENSIONS_END, start)
    block = source[start:end].strip()
    lines = block.splitlines()
    if len(lines) < 3 or lines[0] != "```json" or lines[-1] != "```":
        raise ValueError("MATHS.md certificate dimensions must be one fenced JSON block")
    payload = "\n".join(lines[1:-1])
    if len(payload.encode("utf-8")) > MAX_CERTIFICATE_AUTHORITY_BYTES:
        raise ValueError("MATHS.md certificate-dimensions block exceeds 8192 bytes")
    try:
        dimensions = json.loads(payload)
    except json.JSONDecodeError as exc:
        raise ValueError(f"MATHS.md certificate dimensions are malformed JSON: {exc.msg}") from exc
    if not isinstance(dimensions, dict) or tuple(dimensions) != CERTIFICATE_DIMENSION_GROUPS:
        raise ValueError(
            f"MATHS.md certificate-dimension groups must be {CERTIFICATE_DIMENSION_GROUPS} in order"
        )
    seen: set[str] = set()
    for group in CERTIFICATE_DIMENSION_GROUPS:
        names = dimensions[group]
        if not isinstance(names, list) or not 1 <= len(names) <= MAX_CERTIFICATE_DIMENSIONS_PER_GROUP:
            raise ValueError(f"MATHS.md certificate group {group!r} requires 1..64 dimensions")
        for name in names:
            if (
                not isinstance(name, str)
                or not name.isascii()
                or not name.isidentifier()
                or not 1 <= len(name.encode("utf-8")) <= 64
            ):
                raise ValueError(f"MATHS.md certificate group {group!r} has an invalid dimension")
            if name in seen:
                raise ValueError(f"MATHS.md certificate dimension {name!r} is duplicated")
            seen.add(name)
    return dimensions


def text(
    *,
    enum: list[str] | None = None,
    empty: bool = False,
    maximum: int | None = None,
    pattern: str | None = None,
) -> dict:
    shape: dict = {"type": "string"}
    if not empty:
        shape["minLength"] = 1
    if maximum is not None:
        shape["maxLength"] = maximum
    if enum is not None:
        shape["enum"] = enum
    if pattern is not None:
        shape["pattern"] = pattern
    return shape


def array(
    items: dict | None = None,
    *,
    minimum: int | None = None,
    maximum: int | None = None,
) -> dict:
    shape: dict = {"type": "array"}
    if items is not None:
        shape["items"] = items
    if minimum is not None:
        shape["minItems"] = minimum
    if maximum is not None:
        shape["maxItems"] = maximum
    return shape


def bounded_text(*, enum: list[str] | None = None) -> dict:
    return text(enum=enum, maximum=MAX_TEXT_BYTES, pattern=r"^[^\x00-\x1f\x7f]+$")


def identifier(*, enum: list[str] | None = None) -> dict:
    return text(
        enum=enum,
        maximum=MAX_IDENTIFIER_BYTES,
        pattern=r"^[A-Za-z0-9][A-Za-z0-9._:-]*$",
    )


def digest() -> dict:
    return text(maximum=71, pattern=r"^(blake3|sha256):[0-9a-f]{64}$")


def integer(*, minimum: int = 0, maximum: int = MAX_U64) -> dict:
    return {"type": "integer", "minimum": minimum, "maximum": maximum}


def number(*, minimum: float = 0.0, maximum: float = 1e300) -> dict:
    return {"type": "number", "minimum": minimum, "maximum": maximum}


def bounded_array(items: dict, *, minimum: int = 0, maximum: int = MAX_TABLE_ROWS) -> dict:
    return array(items, minimum=minimum, maximum=maximum)


def ref(kind: str) -> dict:
    return {"$ref": f"{kind}.json"}


def record(
    title: str,
    question: str,
    properties: dict[str, dict],
    *,
    optional: tuple[str, ...] = (),
) -> dict:
    return {
        "$schema": SCHEMA_DIALECT,
        "$comment": f"{GENERATED_NOTE}; authority: {question}",
        "title": title,
        "type": "object",
        "additionalProperties": False,
        "properties": properties,
        "required": sorted(set(properties) - set(optional)),
    }


def q77_properties() -> dict[str, dict]:
    """Return the one bounded structural definition for every Q77 field."""

    bounded_strings = {**bounded_array(bounded_text(), maximum=64), "uniqueItems": True}
    return {
        "cassette_protocol": bounded_text(),
        "adapter_version": bounded_text(),
        "model_revision": digest(),
        "source_parent": digest(),
        "execution_mode": bounded_text(),
        "plan_id": digest(),
        "performance_tier": bounded_text(),
        "training_tier": bounded_text(),
        "modalities": bounded_strings,
        "input_limits": {
            "type": "object",
            "additionalProperties": False,
            "minProperties": 1,
            "maxProperties": 64,
            "patternProperties": {
                r"^[^\x00-\x1f\x7f]{1,512}$": integer(),
            },
        },
        "context_limit": integer(minimum=1),
        "reasoning_fields": bounded_strings,
        "reasoning_history_policy": bounded_text(),
        "tool_schema": {"anyOf": [digest(), {"type": "null"}]},
        "structured_output": {"type": "boolean"},
        "sampling": bounded_strings,
        "streaming": {"type": "boolean"},
        "cancellation": {"type": "boolean"},
        "conversation_state_contract": bounded_text(),
    }


Q77_PROVENANCE = record(
    "Q77 field provenance",
    "Q77",
    {
        "status": text(enum=Q77_PROVENANCE_STATUSES, maximum=32),
        "evidence": digest(),
    },
)
Q77_FIELD_PROVENANCE = {
    "type": "object",
    "additionalProperties": False,
    "properties": {field: ref("capability_field_provenance") for field in Q77_FIELDS},
    "required": sorted(Q77_FIELDS),
}
Q77_PROFILE_PROVENANCE = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        **{field: ref("capability_field_provenance") for field in Q77_FIELDS},
        "precision": ref("capability_field_provenance"),
        "semantic_state": ref("capability_field_provenance"),
    },
    "required": sorted((*Q77_FIELDS, "precision", "semantic_state")),
}


REMOTE_FIELD = record(
    "Remote metadata field",
    "Q50",
    {
        "value": {},
        "trust": text(enum=["ABSENT", "DECLARED", "EVIDENCE_DIGESTED", "PARSED"]),
        "authority": text(),
    },
    optional=("value",),
)

CONDITION_METRIC = record(
    "Condition metric",
    "Q19/MATHS section 1",
    {
        "condition_id": identifier(),
        "provenance_digest": digest(),
        "metric_digest": digest(),
        "positive_definite_witness_digest": digest(),
    },
)
SERVICE_FACE = record(
    "Atom service face",
    "Q19/MATHS section 2",
    {
        "face_id": identifier(),
        "condition_ids": bounded_array(identifier(), minimum=1),
    },
)
MINIMAL_NONFACE = record(
    "Compatibility minimal nonface",
    "Q19/MATHS section 2",
    {
        "nonface_id": identifier(),
        "condition_ids": bounded_array(identifier(), minimum=1),
        "witness_digest": digest(),
    },
)
COVER_ENTRY = record(
    "Protected-condition atom cover entry",
    "Q19/MATHS section 2",
    {"condition_id": identifier(), "atom_id": identifier()},
)
EXCLUDED_CONDITION = record(
    "Causally excluded condition",
    "Q19/MATHS section 8",
    {
        "condition_id": identifier(),
        "cause": bounded_text(
            enum=[
                "OFF_SUPPORT",
                "UNSUPPORTED_MODALITY",
                "UNSUPPORTED_OPERATOR",
                "UNREPRESENTABLE_WITHIN_BOUND",
            ]
        ),
        "evidence_digest": digest(),
    },
)
WITNESS_LOSS = record(
    "Condition-wise witness loss",
    "Q19/MATHS sections 1 and 8",
    {"condition_id": identifier(), "loss": number()},
)
DESCRIPTION = record(
    "Resident description and residual relation",
    "Q19/MATHS sections 5 and 8",
    {
        "class": bounded_text(
            enum=[
                "BLOCK",
                "DENSE_RANK_CONSTRAINED",
                "EXACT",
                "PRODUCT_DICTIONARY",
                "QUANTIZED",
                "SHARED_CORE",
                "SPARSE_DICTIONARY",
                "UNBOUNDED_NET",
            ]
        ),
        "reconstruction_digest": digest(),
        "residual_relation_digest": digest(),
        "distortion_bound": number(),
        "estimator_digest": digest(),
        "estimator_calibration_digest": digest(),
        "sampling_law_id": identifier(),
    },
)
ATOM = record(
    "Compatibility atom",
    "Q19/MATHS sections 2 and 8",
    {
        "atom_id": identifier(),
        "witness_digest": digest(),
        "rank": integer(minimum=1),
        "service_face_id": identifier(),
        "witness_losses": bounded_array(WITNESS_LOSS, minimum=1),
        "description": DESCRIPTION,
    },
)
SAMPLING_LAW = record(
    "Exact or fresh stochastic execution law",
    "Q19/MATHS sections 5 and 8",
    {
        "sampling_law_id": identifier(),
        "kind": bounded_text(enum=["EXACT", "FRESH_RANDOM"]),
        "law_digest": digest(),
        "work_unit": bounded_text(enum=["BYTES", "COLUMNS", "PAGES", "ROWS", "SCALARS"]),
        "seed_policy": bounded_text(enum=["NONE", "RECORDED_COUNTER_KEY"]),
    },
)
OPERATION_COMPOSITION = record(
    "Operation-specific rank and loss composition",
    "Q19/MATHS section 6",
    {
        "operation_id": identifier(),
        "operator_case_id": identifier(),
        "rank_accounting_digest": digest(),
        "loss_propagation_digest": digest(),
        "remainder_bound": number(),
        "epsilon_exec": number(),
        "delta_exec": number(maximum=1.0),
        "sampling_law_id": identifier(),
    },
)
RESOURCE_VECTOR = record(
    "Separate mathematical and physical resource bounds",
    "Q19/MATHS section 8",
    {
        "eta_rep": number(),
        "epsilon_exec": number(),
        "delta_exec_total": number(maximum=1.0),
        "atom_count": integer(minimum=1),
        "max_atom_rank": integer(minimum=1),
        "description_bytes_peak": integer(),
        "description_bytes_total": integer(),
        "metadata_bytes_peak": integer(),
        "metadata_bytes_total": integer(),
        "fresh_samples_max": integer(),
        "fresh_samples_total": integer(),
        "fresh_traffic_max": integer(),
        "fresh_traffic_total": integer(),
        "fresh_traffic_unit": bounded_text(enum=["BYTES", "SCALARS"]),
        "horizon": integer(minimum=1),
    },
)
ATOM_RESOURCE = record(
    "Per-atom resource row",
    "Q19/MATHS section 8",
    {
        "atom_id": identifier(),
        "description_bytes": integer(),
        "metadata_bytes": integer(),
        "fresh_samples_max": integer(),
        "fresh_samples_total": integer(),
        "fresh_traffic_max": integer(),
        "fresh_traffic_total": integer(),
        "epsilon_exec": number(),
        "delta_exec": number(maximum=1.0),
    },
)
OPERATION_RESOURCE = record(
    "Per-operation resource row",
    "Q19/MATHS section 8",
    {
        "operation_id": identifier(),
        "description_bytes_peak": integer(),
        "description_bytes_total": integer(),
        "metadata_bytes_peak": integer(),
        "metadata_bytes_total": integer(),
        "fresh_samples_max": integer(),
        "fresh_samples_total": integer(),
        "fresh_traffic_max": integer(),
        "fresh_traffic_total": integer(),
        "epsilon_exec": number(),
        "delta_exec": number(maximum=1.0),
    },
)
TRACE_STEP_RESOURCE = record(
    "Per-trace-step resource row",
    "Q19/MATHS section 8",
    {
        "step": integer(),
        "operation_id": identifier(),
        "atom_id": identifier(),
        "description_bytes_resident": integer(),
        "metadata_bytes_resident": integer(),
        "fresh_samples": integer(),
        "fresh_traffic": integer(),
        "epsilon_exec": number(),
        "delta_exec": number(maximum=1.0),
    },
)
PHYSICAL_CONVERSION_ROW = record(
    "Mathematical-probe physical conversion",
    "Q19/MATHS section 8",
    {
        "operation_id": identifier(),
        "probe_unit": bounded_text(enum=["BLOCKS", "BYTES", "COLUMNS", "ROWS", "SCALARS"]),
        "probes": integer(),
        "page_reads": integer(),
        "bytes": integer(),
        "memory_bytes_peak": integer(),
        "latency_ns_peak": integer(),
    },
)
PRIOR_MODE_FAILURE = record(
    "Q40 prior-mode failure",
    "Q40",
    {
        "ordinal": integer(minimum=1, maximum=4),
        "mode": bounded_text(enum=Q40_MODES[:-1]),
        "q38_record_digest": digest(),
    },
)

MATHEMATICAL_CERTIFICATE = record(
    "Q19 mathematical resource certificate",
    "Q19/Q33/Q40/MATHS",
    {
        "certificate_version": bounded_text(enum=["q19-v1"]),
        "certificate_id": digest(),
        "target": record(
            "Immutable target and flattening",
            "Q19/MATHS section 1",
            {
                "target_digest": digest(),
                "flattening_digest": digest(),
                "shape": array(integer(minimum=1), minimum=2, maximum=2),
                "field": bounded_text(enum=["COMPLEX", "REAL"]),
            },
        ),
        "condition_metrics": bounded_array(CONDITION_METRIC, minimum=1),
        "compatibility": record(
            "Compatibility complex and atom cover",
            "Q19/MATHS sections 1 and 2",
            {
                "eta_rep": number(),
                "rank_budget": integer(minimum=1),
                "service_faces": bounded_array(SERVICE_FACE, minimum=1),
                "minimal_nonfaces": bounded_array(MINIMAL_NONFACE),
                "cover": bounded_array(COVER_ENTRY, minimum=1),
                "excluded_conditions": bounded_array(EXCLUDED_CONDITION),
            },
        ),
        "atoms": bounded_array(ATOM, minimum=1),
        "description_contract": record(
            "Description, distortion, residual, and estimator family",
            "Q19/MATHS sections 5 and 8",
            {
                "description_family_digest": digest(),
                "distortion_metric_digest": digest(),
                "residual_family_digest": digest(),
                "estimator_family_digest": digest(),
            },
        ),
        "observation_contract": record(
            "Protected observation and rejection contract",
            "Q19/MATHS section 7",
            {
                "kind": bounded_text(enum=["PROTECTED_DECISION_FAMILY", "PROTECTED_TEST_LAW"]),
                "experiment_digest": digest(),
                "support_digest": digest(),
                "selector_digest": digest(),
                "loss_family_digest": digest(),
                "sample_count": integer(),
                "confidence": number(maximum=1.0),
                "off_support": bounded_text(enum=["REJECT"]),
            },
        ),
        "execution_contract": record(
            "Fresh execution and operation-specific composition",
            "Q19/MATHS sections 5 and 6",
            {
                "sampling_laws": bounded_array(SAMPLING_LAW, minimum=1),
                "operations": bounded_array(OPERATION_COMPOSITION, minimum=1),
                "risk_composition_kind": bounded_text(
                    enum=["DECLARED_DEPENDENCE", "DETERMINISTIC", "INDEPENDENT_PRODUCT", "UNION_BOUND"]
                ),
                "risk_composition_digest": digest(),
            },
        ),
        "trace_contract": record(
            "Protected traces and certified horizon",
            "Q19/MATHS section 6",
            {
                "protected_trace_family_digest": digest(),
                "schedule_digest": digest(),
                "prefix_policy": bounded_text(enum=["COHERENT_RESTRICTION", "NO_PREFIX_CLAIM"]),
                "horizon": integer(minimum=1),
            },
        ),
        "resources": RESOURCE_VECTOR,
        "resource_tables": record(
            "Recomputable resource tables",
            "Q19/MATHS section 8",
            {
                "per_atom": bounded_array(ATOM_RESOURCE, minimum=1),
                "per_operation": bounded_array(OPERATION_RESOURCE, minimum=1),
                "per_trace_step": bounded_array(TRACE_STEP_RESOURCE, minimum=1),
            },
        ),
        "physical_conversion": record(
            "Mathematical-to-physical conversion",
            "Q19/MATHS section 8",
            {
                "conversion_rows": bounded_array(PHYSICAL_CONVERSION_ROW, minimum=1),
                "conversion_digest": digest(),
            },
        ),
    },
)

OPERATOR_DISPATCH = record(
    "Pinned MLX operator dispatch",
    "Q30",
    {
        "dispatch_version": bounded_text(enum=["q30-v1"]),
        "runtime_name": bounded_text(enum=[MLX_RUNTIME["name"]]),
        "runtime_version": bounded_text(enum=[MLX_RUNTIME["package"].split("==", 1)[1]]),
        "runtime_commit": text(maximum=40, pattern=r"^[0-9a-f]{40}$"),
        "dispatch_digest": digest(),
        "case_ids": bounded_array(identifier(), minimum=1),
        "apple_features": array(
            bounded_text(enum=MLX_RUNTIME["apple_features"]), minimum=2, maximum=2
        ),
    },
)

EXECUTION_PLAN = record(
    "Compiled certified execution plan",
    "Q33/Q40",
    {
        "plan_version": bounded_text(enum=["compiled-plan-v1"]),
        "plan_id": digest(),
        "selected_mode": bounded_text(enum=[Q40_MODES[-1]]),
        "prior_mode_failures": array(PRIOR_MODE_FAILURE, minimum=4, maximum=4),
        "target_digest": digest(),
        "profile_digest": digest(),
        "certificate_id": digest(),
        "tensor_graph_digest": digest(),
        "page_map_digest": digest(),
        "layout_digest": digest(),
        "precision_planes_digest": digest(),
        "semantic_manifest_digest": digest(),
        "invalidation_graph_digest": digest(),
        "dispatch": OPERATOR_DISPATCH,
        "resource_limits": RESOURCE_VECTOR,
        "artifact_refs": bounded_array(digest(), minimum=1),
        "weight_payload_bytes": integer(maximum=0),
    },
)


def implemented_certificate_dimensions() -> dict[str, list[str]]:
    """Describe the certificate fields implemented by the generated schemas."""
    certificate = MATHEMATICAL_CERTIFICATE["properties"]
    envelope = {
        "certificate_version",
        "certificate_id",
        "resources",
        "resource_tables",
        "physical_conversion",
    }
    return {
        "mathematics": [name for name in certificate if name not in envelope],
        "resources": list(certificate["resources"]["properties"]),
        "tables": list(certificate["resource_tables"]["properties"]),
        "physical": list(certificate["physical_conversion"]["properties"]),
    }


def verify_certificate_dimensions(dimensions: dict[str, list[str]]) -> None:
    """Reject any MATHS.md dimension that the implemented schema does not represent exactly."""
    implemented = implemented_certificate_dimensions()
    for group in CERTIFICATE_DIMENSION_GROUPS:
        authority = set(dimensions[group])
        schema = set(implemented[group])
        if authority != schema:
            raise ValueError(
                f"MATHS.md certificate group {group!r} disagrees with schema: "
                f"authority_only={sorted(authority - schema)}, schema_only={sorted(schema - authority)}"
            )

CONTRACTS: dict[str, dict] = {
    "error": record(
        "Canonical error",
        "Q6/Q32",
        {
            "code": text(enum=sorted(errors.CODES)),
            "object_id": text(),
            "failed_invariant": text(),
            "retryability": text(enum=sorted(errors.RETRYABILITY)),
            "detail": text(empty=True),
        },
    ),
    "request": record(
        "Control request",
        "Q6",
        {
            "protocol_version": text(),
            "operation": text(),
            "idempotency_key": text(),
            "target": text(),
            "arguments": {"type": "object"},
        },
        optional=("target",),
    ),
    "operation": record(
        "Asynchronous operation",
        "Q6",
        {
            "operation_id": text(),
            "kind": text(),
            "state": text(
                enum=["CANCELLED", "FAILED", "PAUSED", "PENDING", "RUNNING", "SUCCEEDED"]
            ),
            "progress": {"type": "number"},
            "result": {"type": "object"},
            "error": ref("error"),
        },
        optional=("result", "error"),
    ),
    "capability_profile": record(
        "Canonical capability profile",
        "Q31",
        {
            "protocol_version": text(),
            "model_refs": array(text()),
            "modalities": array(text()),
            "context": {"type": "object"},
            "reasoning": {},
            "tools": {},
            "structured_output": {},
            "streaming": {},
            "cancellation": {},
            "training": {},
            "source": {},
            "performance_tiers": array({"type": "object"}),
        },
    ),
    "capability_field_provenance": Q77_PROVENANCE,
    "capability_request": record(
        "Q77 capability request",
        "Q77",
        {
            "model_ref": bounded_text(),
            **q77_properties(),
        },
        optional=tuple(Q77_FIELDS),
    ),
    "callable_capability": record(
        "Q77 callable capability",
        "Q77",
        {
            **q77_properties(),
            "precision": bounded_text(),
            "semantic_state": digest(),
            "field_provenance": Q77_PROFILE_PROVENANCE,
        },
    ),
    "negotiated_capability": record(
        "Q77 negotiated capability",
        "Q77",
        {
            **q77_properties(),
            "field_provenance": Q77_FIELD_PROVENANCE,
            "negotiation_id": digest(),
        },
    ),
    "run_request": record(
        "Canonical run request",
        "Q31",
        {
            "idempotency_key": text(),
            "model_ref": text(),
            "input": {},
            "context_ref": text(),
            "generation": {"type": "object"},
            "reasoning": {},
            "output_schema": {"type": "object"},
            "tools": array({"type": "object"}),
        },
        optional=("context_ref", "reasoning", "output_schema", "tools"),
    ),
    "run_event": record(
        "Canonical run event",
        "Q6/Q31",
        {
            "run_id": text(),
            "sequence": {"type": "integer", "minimum": 0},
            "type": text(
                enum=[
                    "started",
                    "reasoning_delta",
                    "output_delta",
                    "tool_call",
                    "tool_result",
                    "usage",
                    "completed",
                    "cancelled",
                    "failed",
                ]
            ),
            "payload": {"type": "object"},
        },
    ),
    "source_descriptor": record(
        "Normalized source descriptor",
        "Q9",
        {
            "kind": text(enum=["huggingface", "ollama", "tinker", "extension"]),
            "locator": text(),
            "revision": text(),
            "artifact_selector": {},
            "credential_ref": text(),
            "license_acceptance_ref": text(),
            "expected_identity": text(),
        },
        optional=(
            "revision",
            "artifact_selector",
            "credential_ref",
            "license_acceptance_ref",
            "expected_identity",
        ),
    ),
    "remote_metadata_field": REMOTE_FIELD,
    "remote_metadata": record(
        "Remote metadata preflight record",
        "Q50",
        {
            **{name: ref("remote_metadata_field") for name in REMOTE_METADATA_FIELDS},
            "conflicts": array(
                record(
                    "Retained metadata conflict",
                    "Q50 acceptance_check",
                    {
                        "field": text(enum=REMOTE_METADATA_FIELDS),
                        "candidates": array(ref("remote_metadata_field"), minimum=2),
                    },
                )
            ),
        },
    ),
    "tensor_span": record(
        "Tensor page span",
        "Q57",
        {
            "page_digest": text(),
            "offset": {"type": "integer", "minimum": 0},
            "length": {"type": "integer", "minimum": 1},
            "tensor_offset": {"type": "integer", "minimum": 0},
        },
    ),
    "tensor_map": record(
        "Semantic tensor map",
        "Q57",
        {
            "semantic_tensor_id": text(),
            "shape": array({"type": "integer", "minimum": 0}),
            "dtype": text(),
            "codec": text(),
            "plane": {},
            "spans": array(ref("tensor_span")),
        },
    ),
    "mathematical_certificate": MATHEMATICAL_CERTIFICATE,
    "operator_dispatch": OPERATOR_DISPATCH,
    "execution_plan": EXECUTION_PLAN,
    "root": {
        **record(
            "Immutable cartridge root manifest",
            "Q57",
            {
                "identity": text(),
                "parents": array(text()),
                "provenance": {"type": "object"},
                "semantic_assets": {"type": "object"},
                "tensor_maps": array(ref("tensor_map")),
                "operators": array(),
                "plans": array(),
                "deltas": array(),
                "integrity_root": text(),
            },
        ),
        "x-cassette-canonicalization": "RFC8785",
    },
}

VALIDATOR_SRC = '''# validator.py — {note}; depends on (none).
"""Validate instances against the generated JSON Schema subset used by Cassette."""

import json
import math
import re
from pathlib import Path

_SCHEMAS = {{}}


def _schemas():
    if not _SCHEMAS:
        for path in sorted(Path(__file__).parent.glob("*.json")):
            if path.name != "MANIFEST.json":
                _SCHEMAS[path.stem] = json.loads(path.read_text(encoding="utf-8"))
    return _SCHEMAS


def _validate(schema, value, path):
    if "$ref" in schema:
        target = Path(schema["$ref"]).stem
        if target not in _schemas():
            return [f"{{path}}: unknown schema reference {{schema['$ref']!r}}"]
        return _validate(_schemas()[target], value, path)
    if "anyOf" in schema:
        if any(not _validate(candidate, value, path) for candidate in schema["anyOf"]):
            return []
        return [f"{{path}}: value does not match any allowed shape"]
    kind = schema.get("type")
    if kind == "object":
        if not isinstance(value, dict):
            return [f"{{path}}: expected object"]
        properties = schema.get("properties", {{}})
        patterns = schema.get("patternProperties", {{}})
        matched = {{
            name: [shape for pattern, shape in patterns.items() if re.fullmatch(pattern, name)]
            for name in value
        }}
        defects = [
            f"{{path}}.{{name}}: unknown field"
            for name in sorted(set(value) - set(properties))
            if schema.get("additionalProperties") is False and not matched[name]
        ]
        if len(value) < schema.get("minProperties", 0):
            defects.append(f"{{path}}: requires at least {{schema['minProperties']}} properties")
        if len(value) > schema.get("maxProperties", len(value)):
            defects.append(f"{{path}}: permits at most {{schema['maxProperties']}} properties")
        defects.extend(
            f"{{path}}.{{name}}: required field missing"
            for name in schema.get("required", [])
            if name not in value
        )
        for name in sorted(set(value) & set(properties)):
            defects.extend(_validate(properties[name], value[name], f"{{path}}.{{name}}"))
        for name in sorted(set(value) - set(properties)):
            for shape in matched[name]:
                defects.extend(_validate(shape, value[name], f"{{path}}.{{name}}"))
        return defects
    if kind == "array":
        if not isinstance(value, list):
            return [f"{{path}}: expected array"]
        defects = []
        if len(value) < schema.get("minItems", 0):
            defects.append(f"{{path}}: requires at least {{schema['minItems']}} items")
        if len(value) > schema.get("maxItems", len(value)):
            defects.append(f"{{path}}: permits at most {{schema['maxItems']}} items")
        if "items" in schema:
            for index, item in enumerate(value):
                defects.extend(_validate(schema["items"], item, f"{{path}}[{{index}}]"))
        if schema.get("uniqueItems") and any(
            item == prior for index, item in enumerate(value) for prior in value[:index]
        ):
            defects.append(f"{{path}}: items must be unique")
        return defects
    if kind == "null":
        return [] if value is None else [f"{{path}}: expected null"]
    expected = {{"string": str, "integer": int, "number": (int, float), "boolean": bool}}.get(kind)
    if expected is not None:
        if isinstance(value, bool) and kind in ("integer", "number"):
            return [f"{{path}}: bool is not a {{kind}}"]
        if not isinstance(value, expected):
            return [f"{{path}}: expected {{kind}}"]
        defects = []
        if kind == "string" and len(value) < schema.get("minLength", 0):
            defects.append(f"{{path}}: string is shorter than {{schema['minLength']}}")
        if kind == "string" and len(value) > schema.get("maxLength", len(value)):
            defects.append(f"{{path}}: string is longer than {{schema['maxLength']}}")
        if kind == "string" and "pattern" in schema and re.fullmatch(schema["pattern"], value) is None:
            defects.append(f"{{path}}: string does not match {{schema['pattern']!r}}")
        if kind == "number" and not math.isfinite(value):
            defects.append(f"{{path}}: number must be finite")
        if "minimum" in schema and value < schema["minimum"]:
            defects.append(f"{{path}}: value is below {{schema['minimum']}}")
        if "maximum" in schema and value > schema["maximum"]:
            defects.append(f"{{path}}: value is above {{schema['maximum']}}")
        if "enum" in schema and value not in schema["enum"]:
            defects.append(f"{{path}}: {{value!r}} not in enum")
        return defects
    if kind is None:
        return []
    return [f"{{path}}: validator does not implement schema type {{kind!r}}"]


def validate(kind, obj):
    """Return every structural defect; an empty list means the instance conforms."""
    if kind not in _schemas():
        return [f"unknown contract kind {{kind!r}}"]
    return _validate(_schemas()[kind], obj, kind)
'''


def emit(outdir: Path) -> dict[str, str]:
    """Write every generated file and return its name-to-SHA-256 integrity map."""
    certificate_dimensions = load_certificate_dimensions()
    verify_certificate_dimensions(certificate_dimensions)
    outdir.mkdir(parents=True, exist_ok=True)
    written: dict[str, str] = {}

    def put(name: str, content: str) -> None:
        (outdir / name).write_text(content, encoding="utf-8")
        written[name] = hashlib.sha256(content.encode("utf-8")).hexdigest()

    for kind, schema in sorted(CONTRACTS.items()):
        document = {"$id": f"{SCHEMA_BASE}/{kind}.json", **schema}
        put(f"{kind}.json", json.dumps(document, ensure_ascii=False, indent=2, sort_keys=True) + "\n")
    tables = (
        f"# tables.py — {GENERATED_NOTE}; depends on (none).\n"
        f"MLX_RUNTIME = {pprint.pformat(MLX_RUNTIME, sort_dicts=True, width=100)}\n"
        f"DISPATCH_DIGEST = {DISPATCH_DIGEST!r}\n"
        f"OPERATOR_DISPATCH = {pprint.pformat(OPERATOR_DISPATCH_RECORD, sort_dicts=True, width=100)}\n"
        f"DISPATCH_ROWS = {pprint.pformat(DISPATCH_ROWS, sort_dicts=True, width=100)}\n"
        f"Q40_MODES = {pprint.pformat(Q40_MODES, sort_dicts=True, width=100)}\n"
        f"Q77_FIELDS = {pprint.pformat(Q77_FIELDS, sort_dicts=True, width=100)}\n"
        f"CERTIFICATE_DIMENSIONS = {pprint.pformat(certificate_dimensions, sort_dicts=True, width=100)}\n"
    )
    put("tables.py", tables)
    put("validator.py", VALIDATOR_SRC.format(note=GENERATED_NOTE))
    (outdir / "MANIFEST.json").write_text(
        json.dumps(written, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return written


def main() -> int:
    outdir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parent.parent / "schema"
    emit(outdir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
